version: '3.3'
services:
  ftp-server:
    image: delfer/alpine-ftp-server
    environment:
      USERS: "user|password"
    ports:
      - "20021:21"
      - "21000-21010:21000-21010"
    networks:
      ftp-uploaders:
        ipv4_address: 11.6.0.5
networks:
  ftp-uploaders:
    driver: bridge
    ipam:
      config:
        - subnet: 11.6.0.0/16
          gateway: 11.6.0.1
