# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - main
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      ftp-server:
        image: delfer/alpine-ftp-server
        env:
          USERS: "user|password"
        ports:
          - 20021:21
          - 21000-21010:21000-21010
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -ldflags "-s -w" -o ./builds/ftp-uploader ./cmd/ftp-uploader/main.go

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: ./builds/ftp-uploader
          retention-days: 5
